[package]
name = "aerin-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = { version = "0.30" }
glutin = { version = "0.32" }
glow = { version = "0.17" }

[dev-dependencies]
glam = { version = "0.33" }
approx = { version = "0.5" }
criterion = { version = "0.8", features = ["html_reports"] }

[[bench]]
name = "vec2"
harness = false
